swagger: "2.0"
info:
  description: This is the swagger file that goes with the server code
  version: "1.0.0"
  title: Swagger Test Python Flask
consumes:
  - application/json
produces:
  - application/json

basePath: /app

paths:
  /managers:
    get:
      operationId: app.controllers.manager_controller.read_all
      tags:
        - Manager
      summary: Read the entire set of managers, sorted by last name
      description: Read the entire set of managers, sorted by last name
      responses:
        200:
          description: Successfully read managers set operation
          schema:
            type: array
            items:
              properties:
                manager_id:
                  type: integer
                  description: Id of the manager
                fname:
                  type: string
                  description: First name of the manager
                lname:
                  type: string
                  description: Last name of the manager
                sites:
                  type: array
                  description: List of the sites associsted to the manager
                  items:
                    properties:
                      site_id:
                        type: integer
                        description: Id of this site
    post:
      operationId: app.controllers.manager_controller.create
      tags:
        - Manager
      summary: Create a manager
      description: Create a new manager
      parameters:
        - name: manager
          in: body
          description: Manager to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of manager to create
              lname:
                type: string
                description: Last name of manager to create
      responses:
        201:
          description: Successfully created manager
          schema:
            properties:
              manager_id:
                type: integer
                description: Id of the manager
              fname:
                type: string
                description: First name of the manager
              lname:
                type: string
                description: Last name of the manager
              sites:
                type: array
                description: List of the sites associsted to the manager
                items:
                  properties:
                    site_id:
                      type: integer
                      description: Id of this site

  /manager/{manager_id}:
    get:
      operationId: app.controllers.manager_controller.read_one
      tags:
        - Manager
      summary: Read one manager
      description: Read one manager
      parameters:
        - name: manager_id
          in: path
          description: Id of the manager to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read manager from managers data operation
          schema:
            type: object
            properties:
              manager_id:
                type: string
                description: Id of the manager
              fname:
                type: string
                description: First name of the manager
              lname:
                type: string
                description: Last name of the manager
              sites:
                type: array
                description: List of the sites associsted to the manager
                items:
                  properties:
                    site_id:
                      type: integer
                      description: Id of this site
    patch:
      operationId: app.controllers.manager_controller.update
      tags:
        - Manager
      summary: Update a manager
      description: Update a manager
      parameters:
        - name: manager_id
          in: path
          description: Id the manager to update
          type: integer
          required: True
        - name: manager
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the manager to update
              lname:
                type: string
                description: Last name of the manager to update
      responses:
        200:
          description: Successfully updated manager
          schema:
            properties:
              manager_id:
                type: string
                description: Id of the manager
              fname:
                type: string
                description: First name of the manager
              lname:
                type: string
                description: Last name of the manager
              sites:
                type: array
                description: List of the sites associsted to the manager
                items:
                  properties:
                    site_id:
                      type: integer
                      description: Id of this site
    delete:
      operationId: app.controllers.manager_controller.delete
      tags:
        - Manager
      summary: Delete a manager from the managers list
      description: Delete a manager
      parameters:
        - name: manager_id
          in: path
          type: integer
          description: Id of the manager to delete
          required: true
      responses:
        204:
          description: Successfully deleted a manager

  /sites:
    get:
      operationId: app.controllers.site_controller.read_all
      tags:
        - Site
      summary: Read the entire set of sites, sorted by name
      description: Read the entire set of sites, sorted by name
      responses:
        200:
          description: Successfully read sites
          schema:
            type: array
            items:
              properties:
                site_id:
                  type: integer
                  description: Id of the site
                name:
                  type: string
                  description: name of this site
                address:
                  type: string
                  description: address of this site
                p_max:
                  type: integer
                  description: maximum electrical power of this site
                assets:
                  type: object
                  description: List of assets associsted to the site
                  properties:
                    asset_id:
                      type: integer
                      description: Id of the asset
                    name:
                      type: string
                      description: Name of the asset
                    type:
                      type: string
                      description: Type of the asset
                    p_nominal:
                      type: integer
                      description: Nominal electrical power of the asset
    post:
      operationId: app.controllers.site_controller.create
      tags:
        - Site
      summary: Create a new site
      description: Create a new site
      parameters:
        - name: site
          in: body
          description: Text content of the site to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: name of this site
              address:
                type: string
                description: address of this site
              p_max:
                type: integer
                description: maximum electrical power of this site
      responses:
        201:
          description: Successfully created a site
          schema:
            type: object
            properties:
              site_id:
                type: integer
                description: Id of the site
              name:
                type: string
                description: name of this site
              address:
                type: string
                description: address of this site
              p_max:
                type: integer
                description: maximum electrical power of this site
              assets:
                type: object
                description: List of assets associsted to the site
                properties:
                  asset_id:
                    type: integer
                    description: Id of the asset
                  name:
                    type: string
                    description: Name of the asset
                  type:
                    type: string
                    description: Type of the asset
                  p_nominal:
                    type: integer
                    description: Nominal electrical power of the asset

  /site/{site_id}:
    get:
      operationId: app.controllers.site_controller.read_one
      tags:
        - Site
      summary: Read a particular site
      description: Read a particular site
      parameters:
        - name: site_id
          in: path
          description: Id of site
          type: integer
          required: True
      responses:
        200:
          description: Successfully read a site
          schema:
            type: object
            properties:
              site_id:
                type: integer
                description: Id of the site
              name:
                type: string
                description: name of this site
              address:
                type: string
                description: address of this site
              p_max:
                type: integer
                description: maximum electrical power of this site
              assets:
                type: object
                description: List of assets associsted to the site
                properties:
                  asset_id:
                    type: integer
                    description: Id of the asset
                  name:
                    type: string
                    description: Name of the asset
                  type:
                    type: string
                    description: Type of the asset
                  p_nominal:
                    type: integer
                    description: Nominal electrical power of the asset
    patch:
      operationId: app.controllers.site_controller.update
      tags:
        - Site
      summary: Update a site
      description: Update a site
      parameters:
        - name: site_id
          in: path
          description: Id of the site
          type: integer
          required: True
        - name: site
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of this site to update
              address:
                type: string
                description: Address of this site to update
              p_max:
                type: integer
                description: Maximum electrical power of this site to update
      responses:
        200:
          description: Successfully updated site
          schema:
            properties:
              site_id:
                type: integer
                description: Id of the site
              name:
                type: string
                description: Name of this site
              address:
                type: string
                description: Address of this site
              p_max:
                type: integer
                description: Maximum electrical power of this site
              assets:
                type: object
                description: List of assets associsted to the site
                properties:
                  asset_id:
                    type: integer
                    description: Id of the asset
                  name:
                    type: string
                    description: Name of the asset
                  type:
                    type: string
                    description: Type of the asset
                  p_nominal:
                    type: integer
                    description: Nominal electrical power of the asset
    delete:
      operationId: app.controllers.site_controller.delete
      tags:
        - Site
      summary: Delete a site
      description: Delete a site
      parameters:
        - name: site_id
          in: path
          description: Id of site
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a site

  /site/{site_id}/add_asset:
    post:
      operationId: app.controllers.asset_controller.create
      tags:
        - Asset
      summary: Create an asset associated with a site
      description: Create an asset associated with a site
      parameters:
        - name: site_id
          in: path
          description: Id of associated site
          type: integer
          required: True
        - name: asset
          in: body
          description: Text content of the asset to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the asset
              type:
                type: string
                description: Type of the asset
              p_nominal:
                type: integer
                description: Nominal electrical power of the asset
      responses:
        201:
          description: Successfully created an asset
          schema:
            type: object
            properties:
              asset_id:
                type: integer
                description: Id of the asset
              name:
                type: string
                description: Name of the asset
              type:
                type: string
                description: Type of the asset
              p_nominal:
                type: integer
                description: Nominal electrical power of the asset

  /site/{site_id}/asset/{asset_id}:
    patch:
      operationId: app.controllers.asset_controller.update
      tags:
        - Asset
      summary: Update an asset of a site
      description: Update an asset of a site
      parameters:
        - name: site_id
          in: path
          description: Id of site associated with asset
          type: integer
          required: True
        - name: asset_id
          in: path
          description: Id of asset
          type: integer
          required: True
        - name: asset
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the asset to update
              type:
                type: string
                description: Type of the asset to update
              p_nomial:
                type: integer
                description: Nominal electrical power of the asset to update
      responses:
        200:
          description: Successfully updated asset
          schema:
            properties:
              asset_id:
                type: integer
                description: Id of the asset
              name:
                type: string
                description: Name of the asset
              type:
                type: string
                description: Type of the asset
              p_nomial:
                type: integer
                description: Nominal electrical power of the asset

    delete:
      operationId: app.controllers.asset_controller.delete
      tags:
        - Asset
      summary: Delete an asset associated with a site
      description: Delete an asset associated with a site
      parameters:
        - name: site_id
          in: path
          description: Id of site associated with asset
          type: integer
          required: True
        - name: asset_id
          in: path
          description: Id of asset
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted an asset
